# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: /[A-Za-z0-9_]+\.[md|txt]/D
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        exclude: /[A-Za-z0-9_]+\.[md|txt|pdb]+
